version: '3.8'
# docker system prune -a --volumes
services:

  web:
    container_name: web
    image: kmtsvetanov/symfony-nginx-php:1.0
    ports:
      - "80:80"

  app:
    container_name: app
    image: kmtsvetanov/symfony-php-composer:1.0
    working_dir: /var/www
    environment:
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      MYSQL_HOST: db
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  db:
    container_name: db
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}

  cache:
    container_name: cache
    image: redis:latest

volumes:
  mysqldata: